version: 0.2
env:
  secrets-manager:
    mock_data_generator_lambda_name: Airbnb_build_keys:mock_data_generator_lambda
    eventbridge_s3_lambda_name: Airbnb_build_keys:eventbridge_s3_lambda
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies for eventbridge lambda function..."
      - pip install -r ./eventbridge_lambda_s3/requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package for mock data generator..."
      - cd mock_data_generator
      - zip -r9 ../buildfiles/artifact_mock_data_generator.zip lambda_function.py
      - echo "Zipping deployment package for eventbridge lambda function..."
      - cd lib
      - zip -r9 ../buildfiles/artifact_eventbridge_lambda.zip .
      - cd ..
      - cd eventbridge_lambda_s3
      - zip -g ../buildfiles/artifact_eventbridge_lambda.zip lambda_function.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp ./buildfiles/ s3://airbnb-sqs-eventbridge-data/buildfiles/ --recursive 
      - echo "Updating Mockgenerator Lambda function via S3..."
      - aws lambda update-function-code --function-name $mock_data_generator_lambda_name --s3-bucket airbnb-sqs-eventbridge-data --s3-key buildfiles/artifact_mock_data_generator.zip
      - echo "Updating EventbridgeS3 Lambda function via S3..."
      - aws lambda update-function-code --function-name $eventbridge_s3_lambda_name --s3-bucket airbnb-sqs-eventbridge-data --s3-key buildfiles/artifact_eventbridge_lambda.zip
      - echo "Deployment complete!"